[package]
name = "dumpo"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.56" , features = ["derive"] }
globset = "0.4.18"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.11"
walkdir = "2.5.0"
